# -*- coding: utf-8 -*-
"""Bindu Miss(Regression).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5fxoFFAAMdzcbX0B8wsq5cmelQ_nWBQ

Statistical Method
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy import stats
from pandas.plotting import scatter_matrix
from statsmodels.formula.api import ols #ordinary least square
from statsmodels.stats.anova import anova_lm

mydata=pd.read_csv('/content/Mult_Reg_Yield.csv')
mydata

scatter_matrix(mydata)
plt.show()

"""Scatter plot using seaborn"""

import seaborn as sns

sns.pairplot(mydata)
plt.show()

#Correlation
mydata.corr()

round(mydata.corr(),3)

t=mydata.Time
tem=mydata.Temperature
out=mydata.Yield

#Develop Linear Regress
model=ols('out ~ t + tem' , mydata).fit() #dependent variable ~ sum of independent variables.
model

#if the p value<0.05, then we will reject the null hypothesis
model.summary()

anova_table=anova_lm(model)
anova_table

#Devolep the model without temp (removing temp because pvalue is 0.702 which is not significant)
model=ols('out~t',mydata).fit()

model.summary()

# to get the predicted values
pred=model.predict()
pred

#To change in to Dataframe format
predy=pd.DataFrame(pred,columns=['Predicted'])
predy

#Residual model
res=model.resid
res

# To convert residual values to dataframe
res1=pd.DataFrame(res,columns=['Residual Values'])
res1

result=mydata.join(predy)
result

result2=result.join(res1)
result2

#MSE
from sklearn.metrics import mean_squared_error

mse=mean_squared_error(out,pred)
mse

#importing math to square
import math

rmse=math.sqrt(mse)
rmse

#Cross validation
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

x=mydata.iloc[:,0:2]
x

model1=LinearRegression()
model1=model1.fit(x,out)

model1

score=cross_val_score(model1,x,out,scoring='neg_mean_squared_error',cv=4)
score

cv_mse=-1*score.mean()
cv_mse

rmse=math.sqrt(cv_mse)
rmse

"""sinse mse is greter than the previous one we continue with the latter


"""